servers:
  emr_persistent_ui:
    default: true
    emr_cluster_arn: "arn:aws:elasticmapreduce:us-east-1:308852840113:cluster/j-11DCSDR26HONW"
    aws_profile: "GDPProdDataInfrastructureSRE-308852840113"
    s3_log_bucket: "grubhub-dl-s3-logging"
    s3_log_path_pattern: "logs/emr_clusters/prod/{cluster_id}/containers/"

mcp:
  transports:
    - stdio
  debug: true