# WARNING: Do not commit your sensitive credentials
servers:
  emr_persistent_ui:
    default: true
    emr_cluster_arn: "arn:aws:elasticmapreduce:us-east-1:<account_id>:cluster/<cluster_id>"

mcp:
  transports: [stdio]
  debug: true